.github/PULL_REQUEST_TEMPLATE.md, .github/workflows/release.yaml, README.md, chart/k8skeycloak-controller/Chart.yaml, chart/k8skeycloak-controller/README.md
* Adds github pr template
* Fix bestpractice badge project url
* Add installation section to readme
* Fix helm readme (repo url/prometheus)
* Only build for linux/amd64, amazoncorretto does not provide other archs and we base off amazoncorretto as we need to execute jars.
=> readme docs / only build for amd64 / pr template

.github/workflows/release-chart.yaml, chart/k8skeycloak-controller/Chart.yaml
=> fix: release chart pipeline

chart/k8skeycloak-controller/Chart.yaml
=> ci(chart): new app version

chart/k8skeycloak-controller/Chart.yaml
=> fix: bump chart

chart/k8skeycloak-controller/Chart.yaml
=> fix: chart version 0.0.0

.github/workflows/main.yaml, .github/workflows/pr-build.yaml, .github/workflows/pr-label.yaml, .github/workflows/rebase.yaml, .github/workflows/release.yaml, chart/k8skeycloak-controller/Chart.yaml
=> fix: chart signing

internal/controllers/keycloakrealm_controller.go
Namespace and Name log fields are uppercase instead lowercase.
Also the req field holds redundant information.
Lowercase fields and remove req.
=> fix: change logging fields

.goreleaser.yaml
=> fix: cosign force yes

README.md, chart/keycloak-controller/templates/clusterrole.yaml
=> fix: chart rbac

README.md, chart/keycloak-controller/templates/clusterrole.yaml
=> fix: rename proxy role

internal/controllers/keycloakrealm_controller.go, internal/controllers/keycloakrealm_controller_test.go
=> fix: recreate existing reconcilers if the realmspec changed

renovate.json
Enable automerge renovate pull requests.
=> ci(renovate): enable automerge patch/minor

api/v1beta1/keycloakrealm_types.go, chart/keycloak-controller/crds/keycloak.infra.doodle.com_keycloakrealms.yaml, config/base/crd/bases/keycloak.infra.doodle.com_keycloakrealms.yaml, internal/controllers/keycloakrealm_controller.go, internal/controllers/keycloakrealm_controller_test.go
=> fix: add new .status.observedSHA256 #164

internal/controllers/keycloakrealm_controller_test.go
=> test: fix conflicting merge issue

CODE_OF_CONDUCT.md, SECURITY.md
=> ci: add code/security policies

config/tests/cases/keycloak-v24/kustomization.yaml
=> test: add v24 e2e test

.github/workflows/rebase.yaml
=> ci: fix rebase job permission

Dockerfile, proxy/Dockerfile
=> fix: pin distroless images

.github/ISSUE_TEMPLATE/VULN-TEMPLATE.md
=> ci: add vulnerbility issue template

.github/ISSUE_TEMPLATE/VULN-TEMPLATE.md
=> ci: fix vuln template

.github/workflows/release.yaml
=> ci: align goreleaser flags with new version

.github/workflows/report-on-vulnerabilities.yaml
=> ci: do not create issue if no vulnerabilties are found

.github/workflows/pr-build.yaml
Python version is 3.7 causing workflows to fail
Update to version 3.13
=> ci: DK-5221 update python version
